### ISSUE TITLE
concurrency error no messages available

### ISSUE THREAD

**Issue by stdweird** [logstash-plugins/logstash-input-lumberjack#68] opened 2015-11-30 10:13 UTC
Possible dupe of #47

Logstash crashes on startup, used to be fine with 1.4.2, fails like this with 2.0.0 (using EL6 based host, rpm installation)

java version used
```
/usr/lib/jvm/jre-1.8.0/bin/java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Logstash output
```
{:timestamp=>"2015-11-30T10:44:01.834000+0100", :message=>"Lumberjack input: unhandled exception", :exception=>#<ConcurrencyError: No message available>, :backtrace=>["org/jruby/ext/thread/ConditionVariable.java:98:in `wait'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/sized_queue_timeout.rb:30:in `push'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/sized_queue_timeout.rb:27:in `push'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:86:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/circuit_breaker.rb:42:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:86:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-2.0.2/lib/logstash/codecs/plain.rb:35:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:82:in `run'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:111:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:372:in `data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:340:in `read_socket'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:363:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:340:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:280:in `data_field_value'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:296:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:332:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:315:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:110:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_1598968638.gen:13:in `run'"], :level=>:error}
```

Logstash config (edited a bit)
```
input {
    gelf {
        type => "remotegelf"
        port => 12201
        remap => true
    }
    
    lumberjack {
        type => "lumberjack"
        ssl_certificate => "/etc/path/to/crt"
        ssl_key => "/etc/path/to/key"
        port => 5043
    }
    
    file {
        tags => [ "httpd", "apache", "web", "http" ]
        type => "httpd"
        path => [ "/var/log/httpd/access_log" ]
        stat_interval => 1
    }
}


filter {
    if [type] == 'remotegelf' {
        mutate {
            split => {
                "tags" => ", "
            }
        }
    }
    
    else if [type] == 'gpfs' {
        grok {
            
            add_field => {
                "program" => "gpfs"
            }
            
            break_on_match => true
            named_captures_only => true
            patterns_dir => [ "/usr/share/grok" ]
            match => {
                "message" => "%{GPFSLOG}"
            }
        }
        
        date {
            match => [ "timestamp", "E MMM dd HH:mm:ss.SSS yyyy", "E MMM  d HH:mm:ss.SSS yyyy" ]
        }
    }
    
    else if [type] == 'httpd' {
        grok {
            add_field => {
                "program" => "httpd"
            }
            
            break_on_match => true
            named_captures_only => true
            patterns_dir => [ "/usr/share/grok" ]
            match => {
                "message" => "%{COMBINEDAPACHELOG}"
            }
        }
        
        date {
            match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
        }
    }
}


output {
    if [type] == 'httpd' {
        gelf {
            host => "remotehost.remotedomain"
            
            ship_metadata => true
            ship_tags => true
            level => [ "info" ]
            custom_fields => {
                "type" => "remotegelf"
            }
            sender => "thishostname"
            port => 12201
        }
    }
    
    else if [type] == 'remotegelf' {
        gelf {
            host => "remotehost.remotedomain"
            
            ship_metadata => true
            ship_tags => true
            level => [ "%{level}" ]
            custom_fields => {
                "type" => "remotegelf"
            }
            facility => "%{facility}"
            port => 12201
        }
    }
}
```

**Comment by prune998** [comment] 2015-12-31 13:19
same issue here, same config !

**Comment by prune998** [comment] 2015-12-31 13:27
It seems I had an issue with the ssl crt/key. Re-generating them solved the issue.

**Comment by ph** [comment] 2016-04-26 16:52
dupe of #47

**Closed by ph** 2016-04-26 16:52 UTC
