### ISSUE TITLE
Logstash completely stops processing logs after a short time

### ISSUE THREAD

**Issue by rabidscorpio** [logstash-plugins/logstash-input-lumberjack#9] opened 2015-03-19 15:23 UTC
I'm running into an issue where logstash will process events for a short period of time before completely failing to the point where no events are processed at all. Restarting the forwarder and logstash has no effect either.  Clients keep trying to connect every second and every time, this error shows up on the server side: (this with --debug)

```
{:timestamp=>"2015-03-19T15:06:00.957000+0000", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
Exception in thread "Ruby-0-Thread-22: /logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:70" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)
```
After a few minutes, the process completely quits with this error:

```
{:timestamp=>"2015-03-19T15:18:03.742000+0000", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
Zlib::BufError: buffer error
              finish at org/jruby/ext/zlib/ZStream.java:134
             inflate at org/jruby/ext/zlib/JZlibInflate.java:72
  compressed_payload at /logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:201
                feed at /logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
                 run at /logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:227
              invoke at /logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:71
```

I've tried this with logstash 1.4.2 and 1.5.0.rc2 and logstash-forwarder 0.3.1 and 0.4.0.  This is my logstash.conf:

```
# Logstash Configuration File
input {
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/data/logstash-forwarder.crt"
    ssl_key => "/data/logstash-forwarder.key"
  }
}

filter {
  if [type] == "rails" {
    grok {
      patterns_dir => ["/data/grok"]
      match => { "message" => "%{RUBY_LOG}" }
    }
    date { match => [ "accept_date", "ISO8601" ] }
  }
  if [type] == "json" {
    json { source => "message" }
    useragent {
      source => "user_agent"
      prefix => "ua."
    }
    geoip { source => "remote_ip" }
  }
  if [type] == "security" or [type] == "syslog" {
    grok {
      patterns_dir => ["/data/grok"]
      match => { "message" => "%{SYSLOGPAMSESSION}" }
      match => { "message" => "%{SYSLOGLINE}" }
    }
  }
  if [type] == "haproxy" {
    grok {
      patterns_dir => ["/data/grok"]
      match => { "message" => "%{HAPROXYHTTP}" }
    }
    date { match => [ "accept_date", "dd/MMM/YYYY:HH:mm:ss.SSS" ] }
  }
  if [type] == "nginx" {
    grok {
      patterns_dir => ["/data/grok"]
      match => { "message" => "%{NGINX_LOG}" }
    }
    date { match => [ "accept_date", "dd/MMM/YYYY:HH:mm:ss Z" ] }
    useragent {
      source => "user_agent"
      prefix => "ua."
    }
    geoip { source => "remote_ip" }
  }
}

output {
  elasticsearch {
    cluster => "elasticsearch"
    host => "elasticsearch"
    protocol => "transport"
  }
}

# Logstash-forwarder config
{
  "network": {
    "servers": [ "logstash.example.com:5000" ],
    "ssl ca":  "/etc/ssl/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [ "/var/log/syslog" ],
      "fields": { "type": "syslog",
                  "project": "project",
                  "environment": "production" }
    }
    ,{
      "paths": [ "/var/log/auth.log" ],
      "fields": { "type": "security",
                  "project": "project",
                  "environment": "production" }
    }
    ,{
      "paths": [ "/var/log/logstash.log" ],
      "fields": { "type": "json",
                  "project": "project",
                  "environment": "production" }
    }
  ]
}
```

**Comment by suyograo** [comment] 2015-03-24 01:02
Interesting, we did fix an issue with Zlib writing partial events: https://github.com/elastic/logstash-forwarder/pull/384 but this was fixed in 0.4.0 LSF.

Can you try running with a combination of LSF 0.4.0 and LS 1.5 RC2  with `--debug` flag? We will try to reproduce in-house too

**Comment by jsvd** [comment] 2015-03-26 18:09
@rabidscorpio do you have very large messages in your data, like a > 150 kbytes line if your logs? are you able to replicate this consistently with a small sample of data that you can share?

**Comment by craig-kennedy** [comment] 2015-03-31 13:23
I am seeing this too.

I am a complete noob to the ELK stack so this may be down to a config issue on my side.

I can see the logs rolling through by using tail on logstash.stdout. It runs for a few minutes then stop. The only way to bring it back on is to kill -9 the logstash service as it wont go down even after using force-stop.

Any help or ideas would be greatly appreciated.

FYI, the only errors I am seeing are:

{:timestamp=>"2015-03-31T14:18:44.110000+0100", :message=>"Failed to flush outgoing items", :outgoing_count=>17, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:440:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:438:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:436:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1507:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
AND
{:timestamp=>"2015-03-31T14:18:27.197000+0100", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:440:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:438:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:436:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.18-java/lib/logstash/outputs/elasticsearch.rb:402:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):2041:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:279:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:235:in `outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `start_outputs'"], :level=>:warn}

**Comment by natxty** [comment] 2015-04-14 17:49
I am experiencing almost exactly the same issue, with the nearly identical exceptions and error messages. Strangely, things were working fine for a week or so, then things started to fail and I've been unable to run everything for longer than a couple of minutes.

My own answer to @jsvd's question to @rabidscorpio is: the message size is small- 2.2k or so each log message. However, the forwarding servers (currently there are 2 servers with logstash-forwarder installed) can be logging a large volume at times (thousands of log events per minute). 

Here are the specifics:
After a very short time starting/restarting Logstash, these begin to appear:
```
Exception in thread "Ruby-0-Thread-195: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:48" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)
```
One per thread, (Ruby-0-Thread-xxx)...

It will also conclude with the above-mentioned buffer error:
```
Zlib::BufError: buffer error
              finish at org/jruby/ext/zlib/ZStream.java:134
             inflate at org/jruby/ext/zlib/JZlibInflate.java:72
  compressed_payload at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:201
                feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:227
              invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:71
```

I am running Logstash 1.5.0.rc2 and Logstash-Forwarder 0.4.0, set up predominately by following the tutorial here: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04

As implied by the tutorial, this is installed on Ubunutu 14.04. If it matters, it's on an AWS EC2 (i2.2xlarge).

I have a minimal configuration, as follows:
```
input {
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/etc/pki/tls/certs/selfsigned.crt"
    ssl_key => "/etc/pki/tls/private/selfsigned.key"
  }
}

filter {
  if [type] == "barkq" {
    json {
        "source" =>"message"
        "target" => "data"
    }

   geoip {
    "source" => "[data][payload][requestHeaders][x-real-ip]"
   }
  }
}

output {
  elasticsearch { host => localhost }
  stdout { codec => rubydebug }
}
```

Logstash forwarder conf:
```
{
  "network": {
    "transport": "tls",
    "servers": [ "XX.XX.XX.XX:5000" ],
    "timeout": 60,
    "ssl ca": "/etc/pki/tls/certs/selfsigned.crt"
  },

  "files": [
    {
        "paths": [
            "/var/log/appserver/appserver.log"
        ],
        "fields": { "type": "barkq" }
    }
  ]
}
```

**Comment by jsvd** [comment] 2015-04-15 14:47
I finished a test run on my laptop without problems :(

Data: ruby script writing random strings of length 300 up to 3000 bytes to two files
Shipper: 2 LSF 0.4.0 instances, each reading 1 file and sending to the same LS
Indexer: 1 instance of LS 1.5.0rc2 (lumberjack -> elasticsearch); no filters
Elasticsearch: 1 node of ES 1.4.4

ES showed an index rate of around 1.5k on my laptop, ran for 1 hour, without problems:

![screen shot 2015-04-15 at 15 44 10](https://cloud.githubusercontent.com/assets/31809/7161283/4a767790-e386-11e4-8fa7-841a50c44df4.png)

That small dip in index rate was when I stopped the ruby script for a few seconds to check if the LSF were lagging behind, then restarted.

I need to come up with a different scenario to test, probably a very filter heavy configuration..

**Comment by kariboe** [comment] 2015-04-23 09:41
Running Logstash 1.5.0.rc2 and Logstash-Forwarder 0.4.0 and experiencing the same behaviour. Process stops after about 10 seconds. 

The error I get: 

    ArgumentError: comparison of String with 1 failed
                   < at org/jruby/RubyComparable.java:168
                   < at org/jruby/RubyString.java:1873
                  [] at file:/opt/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/java_ext/java.util.rb:82
          initialize at /opt/logstash/lib/logstash/event.rb:62
              decode at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.6/lib/logstash/codecs/json.rb:35
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:49
                call at org/jruby/RubyProc.java:271
              invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:72
                call at org/jruby/RubyProc.java:271
                data at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:251
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:230
    data_field_value at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:189
                feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
    compressed_payload at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:205
                feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:227
              invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:71

I have a collectd and lumberjack input - NO filters at the moment - and Elasticsearch output. 
After some testing I found out that removing the option codec => json from the lumberjack input section all works fine. I see some of the others here have a json filter they are using. Maybe the bug is situated there?

**Comment by driskell** [comment] 2015-04-23 09:53
@kariboe Can you give an example event? It looks like your event is a Javascript Array as opposed to an Object. Logstash only works with Objects and looking at the error and the code it looks like this would explain the problem. Logstash attempts to access data["@version"] but data is an array with 1 element. So when it does bounds check, it checks is "@version" less than 1 and this results in the error.

I'd class it as a bug in the JSON filter and JSON codec - if the above is confirmed I suggest raising this as a bug on those repositories (logstash-plugins/logstash-filter-json and logstash-plugins/logstash-codec-json) to make them check for Array and wrap it with an Object:

  {"message"=>["array"]}

**Comment by kariboe** [comment] 2015-04-23 11:52
@Driskell: thanks for the quick reply and investigation into the problem. Here is a example event

     {"@timestamp": "2015-04-23T03:36:06+0200","@version": "1","tags":["proxy"],"message": "xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx - [23/Apr/2015:03:36:06 +0200] \"POST /user/php/ajax/leave.php HTTP/1.1\" 200 20","host": "xxx.xxx.xxx.xxx","forwarded": "xxx.xxx.xxx.xxx","request": "/user/php/ajax/leave.php","urlpath": "/user/php/ajax/leave.php","urlquery": "","method": "POST","status": 200,"bytes": 20,"referer": "https://my_site_com/index.php","useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5","process": "1989","duration": 67920201,"vhost": "xxx.xxx.xx"}

I followed a blog post where someone suggested to let Apache output JSON events directly in stead of letting logstash grokking the access logs. What am I doing wrong?

**Comment by driskell** [comment] 2015-04-23 11:55
@kariboe Is that not the event AFTER it's been processed? It's probably one that worked and is not a problem, nor the one that caused the issue. Do you have your Apache config for the logging? Maybe it will help.

**Comment by kariboe** [comment] 2015-04-23 12:01
@driskell: no this is what my apache write to its access logs. Those logs are being sent to logstash trough logstash-forwarder and there is I have the following input filter:

    input {
       lumberjack {
         port => 5000
         type => "logs"
         codec => json
         ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
         ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
      }
    }

Using the codec => json option I don't have to grok the event anymore inside logstash.

**Comment by kariboe** [comment] 2015-04-23 12:48
@driskell: this was my inspiration:

http://untergeek.com/2013/09/11/getting-apache-to-output-json-for-logstash-1-2-x/

**Comment by blairn** [comment] 2015-07-13 02:39
ok, I think we have the simpliest setup which is failing.... - here is the config we are using...

  input {
    redis {
      host => "localhost"
      data_type => "list"
      key => "dalek"
    }
  }

filter {
}

output {
  # stdout { codec => rubydebug }
  elasticsearch {
    host => "localhost"
    protocol => "http"
  }
}

**Comment by splashx** [comment] 2015-08-05 16:39
After adding ```codec => line { charset => "CP1252" }``` to my input session I also experience this problem.

**Comment by AdeMiller** [comment] 2015-08-21 06:52
Is this still an issue? I am seeing similar behavior with Logstash 1.5.4-1
```
more logstash.err 
Exception in thread "Ruby-0-Thread-96: /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:92" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Unknown Source)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ph** [comment] 2015-08-21 20:22
@AdeMiller Can you post your configuration? 
By looking at the stacktrace this error is coming from a periodic `Stud::Buffer` flush, which could be either coming from the elasticsearch output, or the lumberjack **output**?

If you are using theses plugins can you create an issue in the right repository including your configuration, last 200 lines of the logs, OS and Java version.

**Comment by untergeek** [comment] 2016-04-26 17:43
As Lumberjack is being deprecated in favor of Filebeat, and the changeover has already begun, I'm going to close this.  If the issue exists and/or persists with the filebeat input plugin, please raise the issue there.

**Closed by untergeek** 2016-04-26 17:43 UTC
Labels: bug
